{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinysystems-operator.fullname" . }}-data
  labels:
    {{- include "tinysystems-operator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
