# permissions for end users to view tinynodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tinynode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: tinynode-viewer-role
rules:
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinynodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinynodes/status
  verbs:
  - get
