# permissions for end users to edit tinytrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tinytracker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: tinytracker-editor-role
rules:
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinytrackers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinytrackers/status
  verbs:
  - get
