## Append samples of your project ##
resources:
- operator_v1alpha1_tinynode.yaml
- operator_v1alpha1_tinymodule.yaml
- operator_v1alpha1_tinytracker.yaml
- operator_v1alpha1_tinysignal.yaml
- operator_v1alpha1_tinyflow.yaml
- operator_v1alpha1_tinyproject.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
