apiVersion: operator.tinysystems.io/v1alpha1
kind: TinySignal
metadata:
  labels:
    app.kubernetes.io/name: tinysignal
    app.kubernetes.io/instance: tinysignal-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: tinysignal-sample
spec:
  # TODO(user): Add fields here
