// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: graph.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphChangeServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GraphChangeServer) Reset() {
	*x = GraphChangeServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphChangeServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphChangeServer) ProtoMessage() {}

func (x *GraphChangeServer) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphChangeServer.ProtoReflect.Descriptor instead.
func (*GraphChangeServer) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GraphChangeServer) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GraphChangeModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	VersionID string `protobuf:"bytes,3,opt,name=VersionID,proto3" json:"VersionID,omitempty"`
}

func (x *GraphChangeModule) Reset() {
	*x = GraphChangeModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphChangeModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphChangeModule) ProtoMessage() {}

func (x *GraphChangeModule) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphChangeModule.ProtoReflect.Descriptor instead.
func (*GraphChangeModule) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GraphChangeModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphChangeModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GraphChangeModule) GetVersionID() string {
	if x != nil {
		return x.VersionID
	}
	return ""
}

type GraphChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*GraphElement    `protobuf:"bytes,1,rep,name=Elements,proto3" json:"Elements,omitempty"`
	Op       GraphChangeOp      `protobuf:"varint,2,opt,name=Op,proto3,enum=server.GraphChangeOp" json:"Op,omitempty"`
	Server   *GraphChangeServer `protobuf:"bytes,3,opt,name=Server,proto3" json:"Server,omitempty"`
	Module   *GraphChangeModule `protobuf:"bytes,4,opt,name=Module,proto3" json:"Module,omitempty"`
}

func (x *GraphChange) Reset() {
	*x = GraphChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphChange) ProtoMessage() {}

func (x *GraphChange) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphChange.ProtoReflect.Descriptor instead.
func (*GraphChange) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GraphChange) GetElements() []*GraphElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GraphChange) GetOp() GraphChangeOp {
	if x != nil {
		return x.Op
	}
	return GraphChangeOp_UPDATE
}

func (x *GraphChange) GetServer() *GraphChangeServer {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GraphChange) GetModule() *GraphChangeModule {
	if x != nil {
		return x.Module
	}
	return nil
}

// any element of an element of the graph (using for storage)
type GraphElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	//string FlowID = 2;
	Node     *Node `protobuf:"bytes,3,opt,name=Node,proto3" json:"Node,omitempty"`
	Edge     *Edge `protobuf:"bytes,4,opt,name=Edge,proto3" json:"Edge,omitempty"`
	Revision int64 `protobuf:"varint,5,opt,name=Revision,proto3" json:"Revision,omitempty"`
}

func (x *GraphElement) Reset() {
	*x = GraphElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphElement) ProtoMessage() {}

func (x *GraphElement) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphElement.ProtoReflect.Descriptor instead.
func (*GraphElement) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GraphElement) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GraphElement) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GraphElement) GetEdge() *Edge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *GraphElement) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_graph_proto protoreflect.FileDescriptor

var file_graph_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0xcc, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x02, 0x4f, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x4f, 0x70,
	0x12, 0x31, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x06, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x06,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x7e, 0x0a, 0x0c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x64, 0x67, 0x65, 0x52, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2d, 0x67, 0x6f, 0x3b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData = file_graph_proto_rawDesc
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(file_graph_proto_rawDescData)
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_proto_goTypes = []interface{}{
	(*GraphChangeServer)(nil), // 0: server.GraphChangeServer
	(*GraphChangeModule)(nil), // 1: server.GraphChangeModule
	(*GraphChange)(nil),       // 2: server.GraphChange
	(*GraphElement)(nil),      // 3: server.GraphElement
	(GraphChangeOp)(0),        // 4: server.GraphChangeOp
	(*Node)(nil),              // 5: server.Node
	(*Edge)(nil),              // 6: server.Edge
}
var file_graph_proto_depIdxs = []int32{
	3, // 0: server.GraphChange.Elements:type_name -> server.GraphElement
	4, // 1: server.GraphChange.Op:type_name -> server.GraphChangeOp
	0, // 2: server.GraphChange.Server:type_name -> server.GraphChangeServer
	1, // 3: server.GraphChange.Module:type_name -> server.GraphChangeModule
	5, // 4: server.GraphElement.Node:type_name -> server.Node
	6, // 5: server.GraphElement.Edge:type_name -> server.Edge
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_node_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_graph_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphChangeServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphChangeModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graph_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_rawDesc = nil
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
