// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package module

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformServiceClient interface {
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	PublishModule(ctx context.Context, in *PublishModuleRequest, opts ...grpc.CallOption) (*PublishModuleResponse, error)
	UpdateModuleVersion(ctx context.Context, in *UpdateModuleVersionRequest, opts ...grpc.CallOption) (*UpdateModuleVersionResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, "/server.PlatformService/GetManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) PublishModule(ctx context.Context, in *PublishModuleRequest, opts ...grpc.CallOption) (*PublishModuleResponse, error) {
	out := new(PublishModuleResponse)
	err := c.cc.Invoke(ctx, "/server.PlatformService/PublishModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) UpdateModuleVersion(ctx context.Context, in *UpdateModuleVersionRequest, opts ...grpc.CallOption) (*UpdateModuleVersionResponse, error) {
	out := new(UpdateModuleVersionResponse)
	err := c.cc.Invoke(ctx, "/server.PlatformService/UpdateModuleVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility
type PlatformServiceServer interface {
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	PublishModule(context.Context, *PublishModuleRequest) (*PublishModuleResponse, error)
	UpdateModuleVersion(context.Context, *UpdateModuleVersionRequest) (*UpdateModuleVersionResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlatformServiceServer struct {
}

func (UnimplementedPlatformServiceServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedPlatformServiceServer) PublishModule(context.Context, *PublishModuleRequest) (*PublishModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishModule not implemented")
}
func (UnimplementedPlatformServiceServer) UpdateModuleVersion(context.Context, *UpdateModuleVersionRequest) (*UpdateModuleVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModuleVersion not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.PlatformService/GetManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_PublishModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).PublishModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.PlatformService/PublishModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).PublishModule(ctx, req.(*PublishModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_UpdateModuleVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModuleVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).UpdateModuleVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.PlatformService/UpdateModuleVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).UpdateModuleVersion(ctx, req.(*UpdateModuleVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _PlatformService_GetManifest_Handler,
		},
		{
			MethodName: "PublishModule",
			Handler:    _PlatformService_PublishModule_Handler,
		},
		{
			MethodName: "UpdateModuleVersion",
			Handler:    _PlatformService_UpdateModuleVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.service.proto",
}
