// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: platform.messages.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerKey       string `protobuf:"bytes,1,opt,name=ServerKey,proto3" json:"ServerKey,omitempty"`       // from ags
	DevMode         bool   `protobuf:"varint,2,opt,name=DevMode,proto3" json:"DevMode,omitempty"`          // not sure about it
	DeveloperKey    string `protobuf:"bytes,3,opt,name=DeveloperKey,proto3" json:"DeveloperKey,omitempty"` //if dev mode is on, developer_key is required, maybe if no modVerID
	Version         string `protobuf:"bytes,6,opt,name=Version,proto3" json:"Version,omitempty"`
	ModuleVersionID string `protobuf:"bytes,7,opt,name=ModuleVersionID,proto3" json:"ModuleVersionID,omitempty"` // from ldflags if any
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestRequest) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

func (x *GetManifestRequest) GetDevMode() bool {
	if x != nil {
		return x.DevMode
	}
	return false
}

func (x *GetManifestRequest) GetDeveloperKey() string {
	if x != nil {
		return x.DeveloperKey
	}
	return ""
}

func (x *GetManifestRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetManifestRequest) GetModuleVersionID() string {
	if x != nil {
		return x.ModuleVersionID
	}
	return ""
}

// @todo - nats auth keys?
type GetManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunnerConfig *RunnerConfig               `protobuf:"bytes,1,opt,name=RunnerConfig,proto3" json:"RunnerConfig,omitempty"`
	Modules      []*ModuleVersion            `protobuf:"bytes,2,rep,name=Modules,proto3" json:"Modules,omitempty"`     // empty if dev mode is on
	Instances    []*ConfigureInstanceRequest `protobuf:"bytes,3,rep,name=Instances,proto3" json:"Instances,omitempty"` // instances to bootstrap
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetRunnerConfig() *RunnerConfig {
	if x != nil {
		return x.RunnerConfig
	}
	return nil
}

func (x *GetManifestResponse) GetModules() []*ModuleVersion {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *GetManifestResponse) GetInstances() []*ConfigureInstanceRequest {
	if x != nil {
		return x.Instances
	}
	return nil
}

type PublishModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                 // by publisher from module info
	Description  string       `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`   // by publisher from module info
	Info         string       `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`                 // from readme.md
	DeveloperKey string       `protobuf:"bytes,4,opt,name=DeveloperKey,proto3" json:"DeveloperKey,omitempty"` // from CI
	Version      string       `protobuf:"bytes,8,opt,name=Version,proto3" json:"Version,omitempty"`           // by publisher
	Components   []*Component `protobuf:"bytes,13,rep,name=Components,proto3" json:"Components,omitempty"`
}

func (x *PublishModuleRequest) Reset() {
	*x = PublishModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishModuleRequest) ProtoMessage() {}

func (x *PublishModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishModuleRequest.ProtoReflect.Descriptor instead.
func (*PublishModuleRequest) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PublishModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishModuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishModuleRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *PublishModuleRequest) GetDeveloperKey() string {
	if x != nil {
		return x.DeveloperKey
	}
	return ""
}

func (x *PublishModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PublishModuleRequest) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

type BuildPushOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Repo     string `protobuf:"bytes,3,opt,name=Repo,proto3" json:"Repo,omitempty"`
	Tag      string `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *BuildPushOptions) Reset() {
	*x = BuildPushOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildPushOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPushOptions) ProtoMessage() {}

func (x *BuildPushOptions) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPushOptions.ProtoReflect.Descriptor instead.
func (*BuildPushOptions) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BuildPushOptions) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BuildPushOptions) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BuildPushOptions) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *BuildPushOptions) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type PublishModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module  *ModuleVersion    `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Options *BuildPushOptions `protobuf:"bytes,2,opt,name=Options,proto3" json:"Options,omitempty"`
}

func (x *PublishModuleResponse) Reset() {
	*x = PublishModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishModuleResponse) ProtoMessage() {}

func (x *PublishModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishModuleResponse.ProtoReflect.Descriptor instead.
func (*PublishModuleResponse) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PublishModuleResponse) GetModule() *ModuleVersion {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *PublishModuleResponse) GetOptions() *BuildPushOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateModuleVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Repo string `protobuf:"bytes,2,opt,name=Repo,proto3" json:"Repo,omitempty"`
	Tag  string `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *UpdateModuleVersionRequest) Reset() {
	*x = UpdateModuleVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModuleVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleVersionRequest) ProtoMessage() {}

func (x *UpdateModuleVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleVersionRequest.ProtoReflect.Descriptor instead.
func (*UpdateModuleVersionRequest) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateModuleVersionRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateModuleVersionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UpdateModuleVersionRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type UpdateModuleVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateModuleVersionResponse) Reset() {
	*x = UpdateModuleVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModuleVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleVersionResponse) ProtoMessage() {}

func (x *UpdateModuleVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleVersionResponse.ProtoReflect.Descriptor instead.
func (*UpdateModuleVersionResponse) Descriptor() ([]byte, []int) {
	return file_platform_messages_proto_rawDescGZIP(), []int{6}
}

var File_platform_messages_proto protoreflect.FileDescriptor

var file_platform_messages_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x1a, 0x14, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x63, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x44, 0x65, 0x76, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x44,
	0x65, 0x76, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0xc0,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x0c, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x2f, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x3e, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x22, 0xd1, 0x01, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x70, 0x0a, 0x10, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x75,
	0x73, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x7a, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12,
	0x32, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x50,
	0x75, 0x73, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x52, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2d, 0x67, 0x6f, 0x3b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_messages_proto_rawDescOnce sync.Once
	file_platform_messages_proto_rawDescData = file_platform_messages_proto_rawDesc
)

func file_platform_messages_proto_rawDescGZIP() []byte {
	file_platform_messages_proto_rawDescOnce.Do(func() {
		file_platform_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_messages_proto_rawDescData)
	})
	return file_platform_messages_proto_rawDescData
}

var file_platform_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_platform_messages_proto_goTypes = []interface{}{
	(*GetManifestRequest)(nil),          // 0: server.GetManifestRequest
	(*GetManifestResponse)(nil),         // 1: server.GetManifestResponse
	(*PublishModuleRequest)(nil),        // 2: server.PublishModuleRequest
	(*BuildPushOptions)(nil),            // 3: server.BuildPushOptions
	(*PublishModuleResponse)(nil),       // 4: server.PublishModuleResponse
	(*UpdateModuleVersionRequest)(nil),  // 5: server.UpdateModuleVersionRequest
	(*UpdateModuleVersionResponse)(nil), // 6: server.UpdateModuleVersionResponse
	(*RunnerConfig)(nil),                // 7: server.RunnerConfig
	(*ModuleVersion)(nil),               // 8: server.ModuleVersion
	(*ConfigureInstanceRequest)(nil),    // 9: server.ConfigureInstanceRequest
	(*Component)(nil),                   // 10: server.Component
}
var file_platform_messages_proto_depIdxs = []int32{
	7,  // 0: server.GetManifestResponse.RunnerConfig:type_name -> server.RunnerConfig
	8,  // 1: server.GetManifestResponse.Modules:type_name -> server.ModuleVersion
	9,  // 2: server.GetManifestResponse.Instances:type_name -> server.ConfigureInstanceRequest
	10, // 3: server.PublishModuleRequest.Components:type_name -> server.Component
	8,  // 4: server.PublishModuleResponse.Module:type_name -> server.ModuleVersion
	3,  // 5: server.PublishModuleResponse.Options:type_name -> server.BuildPushOptions
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_platform_messages_proto_init() }
func file_platform_messages_proto_init() {
	if File_platform_messages_proto != nil {
		return
	}
	file_module_version_proto_init()
	file_runner_config_proto_init()
	file_instance_proto_init()
	file_cmp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_platform_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetManifestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildPushOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModuleVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModuleVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_messages_proto_goTypes,
		DependencyIndexes: file_platform_messages_proto_depIdxs,
		MessageInfos:      file_platform_messages_proto_msgTypes,
	}.Build()
	File_platform_messages_proto = out.File
	file_platform_messages_proto_rawDesc = nil
	file_platform_messages_proto_goTypes = nil
	file_platform_messages_proto_depIdxs = nil
}
