// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: port-config.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From                 string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`                                 // full port name, may be empty for a node's own config
	PortName             string `protobuf:"bytes,2,opt,name=PortName,proto3" json:"PortName,omitempty"`                         // port name of a node being configured
	Configuration        []byte `protobuf:"bytes,3,opt,name=Configuration,proto3" json:"Configuration,omitempty"`               // json encoded data, not necessarily an object
	Schema               []byte `protobuf:"bytes,5,opt,name=Schema,proto3" json:"Schema,omitempty"`                             // port schema which might be customized
	SchemaDefault        []byte `protobuf:"bytes,6,opt,name=SchemaDefault,proto3" json:"SchemaDefault,omitempty"`               // default json schema of the port (for the reset)
	ConfigurationDefault []byte `protobuf:"bytes,7,opt,name=ConfigurationDefault,proto3" json:"ConfigurationDefault,omitempty"` // default configuration of the port (for the reset)
}

func (x *PortConfig) Reset() {
	*x = PortConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortConfig) ProtoMessage() {}

func (x *PortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_port_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortConfig.ProtoReflect.Descriptor instead.
func (*PortConfig) Descriptor() ([]byte, []int) {
	return file_port_config_proto_rawDescGZIP(), []int{0}
}

func (x *PortConfig) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PortConfig) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *PortConfig) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *PortConfig) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *PortConfig) GetSchemaDefault() []byte {
	if x != nil {
		return x.SchemaDefault
	}
	return nil
}

func (x *PortConfig) GetConfigurationDefault() []byte {
	if x != nil {
		return x.ConfigurationDefault
	}
	return nil
}

var File_port_config_proto protoreflect.FileDescriptor

var file_port_config_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6f, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xd4, 0x01, 0x0a, 0x0a,
	0x50, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x32,
	0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x67,
	0x6f, 0x3b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_port_config_proto_rawDescOnce sync.Once
	file_port_config_proto_rawDescData = file_port_config_proto_rawDesc
)

func file_port_config_proto_rawDescGZIP() []byte {
	file_port_config_proto_rawDescOnce.Do(func() {
		file_port_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_port_config_proto_rawDescData)
	})
	return file_port_config_proto_rawDescData
}

var file_port_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_port_config_proto_goTypes = []interface{}{
	(*PortConfig)(nil), // 0: server.PortConfig
}
var file_port_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_port_config_proto_init() }
func file_port_config_proto_init() {
	if File_port_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_port_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_port_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_port_config_proto_goTypes,
		DependencyIndexes: file_port_config_proto_depIdxs,
		MessageInfos:      file_port_config_proto_msgTypes,
	}.Build()
	File_port_config_proto = out.File
	file_port_config_proto_rawDesc = nil
	file_port_config_proto_goTypes = nil
	file_port_config_proto_depIdxs = nil
}
