// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: runner-config.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID    string `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	DevMode     bool   `protobuf:"varint,2,opt,name=DevMode,proto3" json:"DevMode,omitempty"`
	WorkspaceID string `protobuf:"bytes,4,opt,name=WorkspaceID,proto3" json:"WorkspaceID,omitempty"`
}

func (x *RunnerConfig) Reset() {
	*x = RunnerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunnerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerConfig) ProtoMessage() {}

func (x *RunnerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runner_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerConfig.ProtoReflect.Descriptor instead.
func (*RunnerConfig) Descriptor() ([]byte, []int) {
	return file_runner_config_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerConfig) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *RunnerConfig) GetDevMode() bool {
	if x != nil {
		return x.DevMode
	}
	return false
}

func (x *RunnerConfig) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

var File_runner_config_proto protoreflect.FileDescriptor

var file_runner_config_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x66, 0x0a,
	0x0c, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x76,
	0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x44, 0x65, 0x76, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x44, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x2d, 0x67, 0x6f, 0x3b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_runner_config_proto_rawDescOnce sync.Once
	file_runner_config_proto_rawDescData = file_runner_config_proto_rawDesc
)

func file_runner_config_proto_rawDescGZIP() []byte {
	file_runner_config_proto_rawDescOnce.Do(func() {
		file_runner_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_runner_config_proto_rawDescData)
	})
	return file_runner_config_proto_rawDescData
}

var file_runner_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_runner_config_proto_goTypes = []interface{}{
	(*RunnerConfig)(nil), // 0: server.RunnerConfig
}
var file_runner_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_config_proto_init() }
func file_runner_config_proto_init() {
	if File_runner_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runner_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunnerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runner_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runner_config_proto_goTypes,
		DependencyIndexes: file_runner_config_proto_depIdxs,
		MessageInfos:      file_runner_config_proto_msgTypes,
	}.Build()
	File_runner_config_proto = out.File
	file_runner_config_proto_rawDesc = nil
	file_runner_config_proto_goTypes = nil
	file_runner_config_proto_depIdxs = nil
}
