# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.tinysystems.io_tinynodes.yaml
- bases/operator.tinysystems.io_tinymodules.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
#- patches/webhook_in_tinymodules.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch
#- patches/cainjection_in_tinymodules.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch
