name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add helm dependencies
        continue-on-error: true
        run: |
          helm repo add tinysystems https://tiny-systems.github.io/module

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        continue-on-error: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
